package small.business.swing.gui;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import org.apache.log4j.Logger;

/**
 *
 * @author ihor
 */
public class AboutJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    static Logger log = Logger.getLogger(AboutJFrame.class.getName());

    /**
     * Creates new form AboutJFrame
     */
    public AboutJFrame() {
        initComponents();
        jLabelJava.setText("Java: " + System.getProperty("java.version") + " " + System.getProperty("java.vendor") + " " + System.getProperty("java.vm.name"));
        jLabelOS.setText("System: " + System.getProperty("os.name") + " version " + System.getProperty("os.version") + " " + System.getProperty("os.arch"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane = new javax.swing.JScrollPane();
		jTextAreaInfo = new javax.swing.JTextArea();
		jTextAreaInfo.setEditable(false);
		jLabelImage = new javax.swing.JLabel();
		jLabelAutorSite = new javax.swing.JLabel();
		jLabelOS = new javax.swing.JLabel();
		jLabelJava = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setName("frameAbout"); // NOI18N
		setResizable(false);
		setType(java.awt.Window.Type.UTILITY);
		jTextAreaInfo.setColumns(20);
		jTextAreaInfo.setLineWrap(true);
		jTextAreaInfo.setRows(5);
		jTextAreaInfo.setText("Small business це безкоштовне програмне забезпечення з відкритим кодом що розповсюджується за ліцензією GNU General Public License v2 чи пізнішою та LGPL.\nВи також можете підтримати проект матеріально чи фінансово:\nНам потрібні: додаткове обладнання для тестування програмного забезпечення та фінанси на оплату електроенергії та інших послуг.\n\nНа даний момент програмне забезпечення працює в слідуючих операційних системах:\nWindows XP/7/8, Linux, MacOS.\n\nDonate/фінансова допомога розвитку проекту\r\nWebMoney\r\nU109404091269 - UAN\r\nZ410354728000 - $\r\nE332626717591 - Euro");
		jTextAreaInfo.setWrapStyleWord(true);
		jTextAreaInfo.setRequestFocusEnabled(false);
		jScrollPane.setViewportView(jTextAreaInfo);

		jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/oldthunderbird.png"))); // NOI18N

		jLabelAutorSite.setForeground(new java.awt.Color(51, 51, 255));
		jLabelAutorSite.setText("http://www.emetemunoy.appspot.com");
		jLabelAutorSite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jLabelAutorSite.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jLabelAutorSiteMouseReleased(evt);
			}
		});

		jLabelOS.setText("System:");

		jLabelJava.setText("Java:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(6, 6, 6).addComponent(jLabelImage).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(10, 10, 10)).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabelAutorSite).addComponent(jLabelJava, javax.swing.GroupLayout.Alignment.LEADING)).addComponent(jLabelOS, javax.swing.GroupLayout.Alignment.LEADING)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabelImage).addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabelAutorSite).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabelJava).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabelOS).addGap(6, 6, 6)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

    private void jLabelAutorSiteMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelAutorSiteMouseReleased
        Desktop desktop = Desktop.getDesktop();
        try {
            java.net.URI uri = new java.net.URI(jLabelAutorSite.getText());
            desktop.browse(uri);
        } catch (URISyntaxException e) {
            log.error(e.getMessage());
        } catch (IOException e) {
            log.error(e.getMessage());
        }
    }// GEN-LAST:event_jLabelAutorSiteMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed"
        // desc=" Look and feel setting code (optional) ">
		/*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel
         * /plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutJFrame().setVisible(true);
            }
        });
    }
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel		jLabelAutorSite;
	private javax.swing.JLabel		jLabelImage;
	private javax.swing.JLabel		jLabelJava;
	private javax.swing.JLabel		jLabelOS;
	private javax.swing.JScrollPane	jScrollPane;
	private javax.swing.JTextArea	jTextAreaInfo;
	// End of variables declaration//GEN-END:variables
}