package small.business.swing.gui.invoices.returnsofgoods;

import config.AppContext;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import org.springframework.context.ApplicationContext;
import small.business.businesslayer.ReturnsOfGoodsService;
import small.business.dao.entity.ReturnsOfGoodsInvoice;
import small.business.swing.gui.utils.ModalFrameUtil;

/**
 *
 * @author root
 */
public class ReturnsOfGoodsListJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    static Logger log = Logger.getLogger(ReturnsOfGoodsListJFrame.class.getName());
    private ApplicationContext ctx = AppContext.getApplicationContext();
    private ReturnsOfGoodsService returnsOfGoodsService = (ReturnsOfGoodsService) ctx.getBean("returnsOfGoodsService");
    private final static int OBJECT_COLUMN = 0;

    /**
     * Creates new form ReturnsOfGoodsListJFrame
     */
    public ReturnsOfGoodsListJFrame() {
        initComponents();
        getList();
    }

    private void getList() {
        DefaultTableModel dataModel = (DefaultTableModel) jTable.getModel();
        dataModel.setRowCount(0);
        try {
            for (ReturnsOfGoodsInvoice returnsOfGoodsInvoice : returnsOfGoodsService.getDataList()) {
                Object[] g = new Object[]{returnsOfGoodsInvoice, (returnsOfGoodsInvoice.getTypeOfReturns() == 0 ? "Повернення постачальнику" : "Повернення від клієнта"), DateFormat.getDateTimeInstance(DateFormat.FULL, DateFormat.SHORT).format(returnsOfGoodsInvoice.getReturningDate()), (returnsOfGoodsInvoice.getCounterParty() != null) ? returnsOfGoodsInvoice.getCounterParty().getTitle() : null, (returnsOfGoodsInvoice.getStoreHouse() != null) ? returnsOfGoodsInvoice.getStoreHouse() : null};
                dataModel.addRow(g);
            }
            jTable.setModel(dataModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Помилка при отриманні списку накладних:\nінформація про помилку знаходиться в logJ.txt", null, JOptionPane.ERROR_MESSAGE);
        }
        svalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClose = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Список товарів на повернення");
        setExtendedState(6);

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/exit.png"))); // NOI18N
        jButtonClose.setText("Вихід");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Вид повернення", "Дата", "Контрагент", "Склад"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableMouseReleased(evt);
            }
        });
        jScrollPane.setViewportView(jTable);
        jTable.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable.getColumnModel().getColumn(0).setMaxWidth(60);

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/add.png"))); // NOI18N
        jButtonAdd.setText("Створити");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/edit.png"))); // NOI18N
        jButtonEdit.setText("Редагувати");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/delete.png"))); // NOI18N
        jButtonRemove.setText("Видалити");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButtonClose)
                .addContainerGap())
            .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonRemove)
                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        returnsOfGoodsService.setCurrentElement(new ReturnsOfGoodsInvoice());
        ReturnsElementJFrame re = new ReturnsElementJFrame();
        re.pack();
        ModalFrameUtil.showAsModal(re, this);
        getList();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        edit();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Так - Повернути товари на склад\nНі - Видалити без повернення товарів на склад", "Видалення запису", JOptionPane.YES_NO_CANCEL_OPTION);
        if (returnsOfGoodsService.isCanRemoveInvoice()) {
            if (confirm == JOptionPane.YES_OPTION) {
                ReturnsOfGoodsInvoice selectedObject = (ReturnsOfGoodsInvoice) jTable.getValueAt(jTable.getSelectedRow(), OBJECT_COLUMN);
                try {
                    returnsOfGoodsService.removeCurrentElement(selectedObject, true);
                } catch (Exception e) {
                    log.error("Try Remove", e);
                    JOptionPane.showMessageDialog(this, "Помилка при видаленні накладної:\nінформація про помилку знаходиться в logJ.txt", null, JOptionPane.ERROR_MESSAGE);
                }
                getList();
            }
            if (confirm == JOptionPane.NO_OPTION) {
                ReturnsOfGoodsInvoice selectedObject = (ReturnsOfGoodsInvoice) jTable.getValueAt(jTable.getSelectedRow(), OBJECT_COLUMN);
                try {
                    returnsOfGoodsService.removeCurrentElement(selectedObject, false);
                } catch (Exception e) {
                    log.error("Try Remove", e);
                    JOptionPane.showMessageDialog(this, "Помилка при видаленні накладної:\nінформація про помилку знаходиться в logJ.txt", null, JOptionPane.ERROR_MESSAGE);
                }
                getList();
            }
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if (evt.getClickCount() == 2) {
            edit();
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseReleased
        svalidate();
    }//GEN-LAST:event_jTableMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed"
        // desc=" Look and feel setting code (optional) ">
		/*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel
         * /plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnsOfGoodsListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnsOfGoodsListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnsOfGoodsListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnsOfGoodsListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ReturnsOfGoodsListJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
    private void svalidate() {
        ReturnsOfGoodsInvoice validateElement = null;
        if (jTable.getSelectedRow() >= 0) {
            validateElement = (ReturnsOfGoodsInvoice) jTable.getValueAt(jTable.getSelectedRow(), OBJECT_COLUMN);

        }
        returnsOfGoodsService.setCurrentElement(validateElement);
        returnsOfGoodsService.validate();
        jButtonEdit.setEnabled(returnsOfGoodsService.isCanEditInvoice());
        jButtonRemove.setEnabled(returnsOfGoodsService.isCanRemoveInvoice());
    }

    private void edit() {
        if (jTable.getSelectedRow() >= 0) {
            ReturnsOfGoodsInvoice selectedObject = (ReturnsOfGoodsInvoice) jTable.getValueAt(jTable.getSelectedRow(), OBJECT_COLUMN);
            returnsOfGoodsService.setCurrentElement(selectedObject);
            ReturnsElementJFrame re = new ReturnsElementJFrame();
            re.pack();
            ModalFrameUtil.showAsModal(re, this);
            getList();
        }
    }
}