/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package small.business.swing.gui.invoices.returnsofgoods;

import config.AppContext;
import org.springframework.context.ApplicationContext;
import small.business.businesslayer.ReturnsOfGoodsService;
import small.business.dao.entity.ReturnsOfGoodsInvoice;
import small.business.swing.gui.utils.ModalFrameUtil;

/**
 * 
 * @author root
 */
public class ReturnsOfGoodsJFrame extends javax.swing.JFrame {
	private static final long		serialVersionUID		= 1L;
	private ApplicationContext		ctx						= AppContext.getApplicationContext();
	private ReturnsOfGoodsService	returnsOfGoodsService	= (ReturnsOfGoodsService) ctx.getBean("returnsOfGoodsService");

	/**
	 * Creates new form ReturnsOfGoodsJFrame
	 */
	public ReturnsOfGoodsJFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButtonNewInvoice = new javax.swing.JButton();
		jButtonInvoicesList = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Повернення товарів");
		setResizable(false);
		setType(java.awt.Window.Type.UTILITY);

		jButtonNewInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/invoice.png"))); // NOI18N
		jButtonNewInvoice.setText("Нове повернення товару");
		jButtonNewInvoice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jButtonNewInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButtonNewInvoice.setMaximumSize(new java.awt.Dimension(175, 161));
		jButtonNewInvoice.setMinimumSize(new java.awt.Dimension(175, 161));
		jButtonNewInvoice.setPreferredSize(new java.awt.Dimension(175, 161));
		jButtonNewInvoice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButtonNewInvoice.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonNewInvoiceActionPerformed(evt);
			}
		});

		jButtonInvoicesList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/invoiceslist.png"))); // NOI18N
		jButtonInvoicesList.setText("Список повернень товарів");
		jButtonInvoicesList.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jButtonInvoicesList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButtonInvoicesList.setMaximumSize(new java.awt.Dimension(175, 161));
		jButtonInvoicesList.setMinimumSize(new java.awt.Dimension(175, 161));
		jButtonInvoicesList.setPreferredSize(new java.awt.Dimension(175, 161));
		jButtonInvoicesList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButtonInvoicesList.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonInvoicesListActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jButtonNewInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButtonInvoicesList, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jButtonInvoicesList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jButtonNewInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));

		getAccessibleContext().setAccessibleDescription("");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonNewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNewInvoiceActionPerformed
		ReturnsOfGoodsInvoice c = new ReturnsOfGoodsInvoice();
		returnsOfGoodsService.setCurrentElement(c);
		ReturnsElementJFrame re = new ReturnsElementJFrame();
		re.pack();
		ModalFrameUtil.showAsModal(re, this);
	}// GEN-LAST:event_jButtonNewInvoiceActionPerformed

	private void jButtonInvoicesListActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonInvoicesListActionPerformed
		ReturnsOfGoodsListJFrame returnsOfGoodsList = new ReturnsOfGoodsListJFrame();
		returnsOfGoodsList.pack();
		ModalFrameUtil.showAsModal(returnsOfGoodsList, this);
		this.dispose();
	}// GEN-LAST:event_jButtonInvoicesListActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel
		 * /plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ReturnsOfGoodsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ReturnsOfGoodsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ReturnsOfGoodsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ReturnsOfGoodsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ReturnsOfGoodsJFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton	jButtonInvoicesList;
	private javax.swing.JButton	jButtonNewInvoice;
	// End of variables declaration//GEN-END:variables
}
