package small.business.swing.gui.nomenclature;

import config.AppContext;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import small.business.businesslayer.NomenclatureService;
import small.business.businesslayer.SettingsService;
import small.business.dao.entity.Nomenclature;
import small.business.swing.gui.utils.ModalFrameUtil;

/**
 *
 * @author ihor
 */
public class NomenclatureListJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private ApplicationContext ctx = AppContext.getApplicationContext();
    private NomenclatureService nomenclatureService = (NomenclatureService) ctx.getBean("nomenclatureService");
    private SettingsService settingsService = (SettingsService) ctx.getBean("settingsService");
    private final static int OBJECT_COLUMN = 2;
    private boolean isSearchMode = false;

    /**
     * Creates new form NomenclatureListJFrame
     */
    public NomenclatureListJFrame() {
        initComponents();
        getList();
    }

    private void getList() {
        DefaultTableModel dataModel = (DefaultTableModel) jTable.getModel();
        dataModel.setRowCount(0);
        List<Nomenclature> dataList;
        if (isSearchMode) {
            dataList = nomenclatureService.getSearchDataList((Long) jSpinnerNomenclatureID.getValue(), jTextFieldSearchNomenclatureByTitle.getText(), jTextFieldSearchByFactorySerialArticul.getText(), jTextFieldSearchByAdditionalArticul.getText());
        } else {
            dataList = nomenclatureService.getDataList();
        }
        for (Nomenclature nomenclature : dataList) {
            Object[] g = new Object[]{(nomenclature.isGroup().equals(Nomenclature.GROUP)) ? "Група" : "-", nomenclature.getId(), nomenclature, nomenclature.getArticleofgoods(), nomenclature.getArticleinside(), nomenclature.getQuantity(), nomenclature.getQuantitymin(), nomenclature.getPrice(), nomenclature.getRetailPrice() == null ? null : (nomenclature.getRetailPrice() * settingsService.getExchangeRate()), nomenclature.getSmallWholeSalePrice() == null ? null : (nomenclature.getSmallWholeSalePrice() * settingsService.getExchangeRate()), nomenclature.getBigWholeSalePrice() == null ? null : (nomenclature.getBigWholeSalePrice() * settingsService.getExchangeRate())};
            dataModel.addRow(g);
        }
        jTable.setModel(dataModel);
        svalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    @SuppressWarnings({"serial","rawtypes","unchecked"})
	private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonAddGroup = new javax.swing.JButton();
        jButtonMove = new javax.swing.JButton();
        jPanelSearch = new javax.swing.JPanel();
        jButtonSearch = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jSpinnerNomenclatureID = new javax.swing.JSpinner();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldSearchNomenclatureByTitle = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelAdditionalArticul = new javax.swing.JLabel();
        jTextFieldSearchByFactorySerialArticul = new javax.swing.JTextField();
        jTextFieldSearchByAdditionalArticul = new javax.swing.JTextField();
        jLabelFactorySerialArticul = new javax.swing.JLabel();
        jButtonClearSearch = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Список номенклатури");
        setExtendedState(6);
        setName("frameNomenclature"); // NOI18N

        jPanel.setName(""); // NOI18N

        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/delete.png"))); // NOI18N
        jButtonDelete.setText("Видалити");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/exit.png"))); // NOI18N
        jButtonClose.setText("Закрити");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/add.png"))); // NOI18N
        jButtonAdd.setText("Створити");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/edit.png"))); // NOI18N
        jButtonEdit.setText("Редагувати");
        jButtonEdit.setEnabled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonAddGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/addgroup.png"))); // NOI18N
        jButtonAddGroup.setText("Створити групу");
        jButtonAddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddGroupActionPerformed(evt);
            }
        });

        jButtonMove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/move.png"))); // NOI18N
        jButtonMove.setText("Перемістити");
        jButtonMove.setEnabled(false);
        jButtonMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClose)
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonSearch.setText("Пошук");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelID.setText("id:");

        jSpinnerNomenclatureID.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), null, Long.valueOf(1L)));

        jLabelTitle.setText("Найменування:");

        jLabelAdditionalArticul.setText("Внутрішній артикул:");

        jLabelFactorySerialArticul.setText("Заводський артикул:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFactorySerialArticul)
                    .addComponent(jTextFieldSearchByFactorySerialArticul, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelAdditionalArticul)
                        .addGap(127, 127, 127))
                    .addComponent(jTextFieldSearchByAdditionalArticul)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdditionalArticul)
                    .addComponent(jLabelFactorySerialArticul)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSearchByFactorySerialArticul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSearchByAdditionalArticul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );

        jButtonClearSearch.setText("Очистити");
        jButtonClearSearch.setEnabled(false);
        jButtonClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerNomenclatureID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSearchNomenclatureByTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClearSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerNomenclatureID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearchNomenclatureByTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClearSearch))
                .addGap(2, 2, 2))
        );

        jTable.setAutoCreateRowSorter(true);
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Група", "id", "Найменування", "Заводський артикул", "Внутрішній артикул", "Кількість", "Мін. кількість", "Ціна", "Роздріб", "Дрібний опт", "Крупний опт"
            }
        ) {
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableMouseReleased(evt);
            }
        });
        jScrollPane.setViewportView(jTable);
        jTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable.getColumnModel().getColumn(0).setMaxWidth(50);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        jTable.getColumnModel().getColumn(1).setMaxWidth(60);
        jTable.getColumnModel().getColumn(2).setMinWidth(200);
        jTable.getColumnModel().getColumn(3).setPreferredWidth(155);
        jTable.getColumnModel().getColumn(3).setMaxWidth(155);
        jTable.getColumnModel().getColumn(4).setPreferredWidth(155);
        jTable.getColumnModel().getColumn(4).setMaxWidth(155);
        jTable.getColumnModel().getColumn(5).setPreferredWidth(75);
        jTable.getColumnModel().getColumn(5).setMaxWidth(75);
        jTable.getColumnModel().getColumn(6).setPreferredWidth(105);
        jTable.getColumnModel().getColumn(6).setMaxWidth(120);
        jTable.getColumnModel().getColumn(7).setMaxWidth(60);
        jTable.getColumnModel().getColumn(8).setMaxWidth(76);
        jTable.getColumnModel().getColumn(9).setMaxWidth(126);
        jTable.getColumnModel().getColumn(10).setMaxWidth(166);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        nomenclatureService.setCurrentElement(new Nomenclature(Nomenclature.NOMENCLATURE));
        NomenclatureElementJFrame nomenclatureElement = new NomenclatureElementJFrame();
        nomenclatureElement.pack();
        ModalFrameUtil.showAsModal(nomenclatureElement, this);
        getList();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonAddGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddGroupActionPerformed
        nomenclatureService.setCurrentElement(new Nomenclature(Nomenclature.GROUP));
        GroupElementJFrame groupElement = new GroupElementJFrame();
        groupElement.pack();
        ModalFrameUtil.showAsModal(groupElement, this);
        getList();

    }//GEN-LAST:event_jButtonAddGroupActionPerformed

    private void jTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseReleased
        svalidate();
    }//GEN-LAST:event_jTableMouseReleased

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if (evt.getClickCount() == 2) {
            Nomenclature selectedObject = (Nomenclature) jTable.getValueAt(jTable.getSelectedRow(), OBJECT_COLUMN);
            nomenclatureService.setCurrentElement(selectedObject);
            if (selectedObject.isGroup().contentEquals(Nomenclature.GROUP)) {
                nomenclatureService.setCurrentCategory(selectedObject);
                getList();
            } else {
                NomenclatureElementJFrame nomenclatureElement = new NomenclatureElementJFrame();
                nomenclatureElement.pack();
                ModalFrameUtil.showAsModal(nomenclatureElement, this);
                getList();
            }
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        Nomenclature selectedObject = (Nomenclature) jTable.getValueAt(jTable.getSelectedRow(), OBJECT_COLUMN);
        nomenclatureService.setCurrentElement(selectedObject);
        if (selectedObject.isGroup().contentEquals(Nomenclature.GROUP)) {
            GroupElementJFrame groupElement = new GroupElementJFrame();
            groupElement.pack();
            ModalFrameUtil.showAsModal(groupElement, this);
        } else {
            NomenclatureElementJFrame nomenclatureElement = new NomenclatureElementJFrame();
            nomenclatureElement.pack();
            ModalFrameUtil.showAsModal(nomenclatureElement, this);
        }
        getList();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Дійсно видалити запис?", "", JOptionPane.YES_NO_OPTION);
        if ((jTable.getSelectedRow() >= 0) && (confirm == JOptionPane.YES_OPTION)) {
            Nomenclature selectedObject = (Nomenclature) jTable.getValueAt(jTable.getSelectedRow(), OBJECT_COLUMN);
            nomenclatureService.removeCurrentElement(selectedObject);
            getList();
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveActionPerformed
        if (jTable.getSelectedRow() >= 0) {
            nomenclatureService.setSelectType(Nomenclature.GROUP);
            NomenclatureSelectJFrame nomenclatureSelect = new NomenclatureSelectJFrame();
            nomenclatureSelect.pack();
            ModalFrameUtil.showAsModal(nomenclatureSelect, this);
            nomenclatureService.move();
            getList();
        }
    }//GEN-LAST:event_jButtonMoveActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        isSearchMode = true;
        jButtonClearSearch.setEnabled(true);
        getList();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearSearchActionPerformed
        jSpinnerNomenclatureID.setValue(0L);
        jTextFieldSearchNomenclatureByTitle.setText("");
        jTextFieldSearchByFactorySerialArticul.setText("");
        jTextFieldSearchByAdditionalArticul.setText("");
        isSearchMode = false;
        jButtonClearSearch.setEnabled(false);
        getList();
    }//GEN-LAST:event_jButtonClearSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NomenclatureListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NomenclatureListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NomenclatureListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NomenclatureListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NomenclatureListJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddGroup;
    private javax.swing.JButton jButtonClearSearch;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonMove;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelAdditionalArticul;
    private javax.swing.JLabel jLabelFactorySerialArticul;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSpinner jSpinnerNomenclatureID;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldSearchByAdditionalArticul;
    private javax.swing.JTextField jTextFieldSearchByFactorySerialArticul;
    private javax.swing.JTextField jTextFieldSearchNomenclatureByTitle;
    // End of variables declaration//GEN-END:variables

    private void svalidate() {
        Nomenclature validateElement = null;
        if (jTable.getSelectedRow() >= 0) {
            validateElement = (Nomenclature) jTable.getValueAt(jTable.getSelectedRow(), OBJECT_COLUMN);
        }
        nomenclatureService.setCurrentElement(validateElement);
        nomenclatureService.validate();
        jButtonEdit.setEnabled(nomenclatureService.isCanEdit());
        jButtonMove.setEnabled(nomenclatureService.isCanMove());
        jButtonDelete.setEnabled(nomenclatureService.isCanRemove());
    }
}