package small.business.swing.gui.storehouses;

import config.AppContext;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

import org.apache.log4j.Logger;
import org.springframework.context.ApplicationContext;

import small.business.businesslayer.ReturnsOfGoodsService;
import small.business.businesslayer.StoreHousesService;
import small.business.dao.entity.GoodsOnStoreHouses;
import small.business.dao.entity.StoreHouse;
import small.business.swing.gui.utils.ModalFrameUtil;

/**
 *
 * @author root
 */
public class StoreHousesJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    static Logger log = Logger.getLogger(ReturnsOfGoodsService.class.getName());
    private ApplicationContext ctx = AppContext.getApplicationContext();
    private StoreHousesService storeHousesService = (StoreHousesService) ctx.getBean("storeHousesService");
    private final static int OBJECT_COLUMN = 1;

    /**
     * Creates new form StoreHousesJFrame
     */
	public StoreHousesJFrame() {
		initComponents();
		try {
			getStoreHousesList();
			getGoodsList();
		}
		catch (Exception e) {
			log.error(e);
		}
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "rawtypes", "serial"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonAddGoods = new javax.swing.JButton();
        jButtonEditGoods = new javax.swing.JButton();
        jPanelStoreHouse = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListStoreHouses = new javax.swing.JList();
        jPanelGoods = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGoods = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Склади");
        setExtendedState(6);
        setName("storeHouse"); // NOI18N

        jButtonAddGoods.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/add.png"))); // NOI18N
        jButtonAddGoods.setText("Додати на склад");
        jButtonAddGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddGoodsActionPerformed(evt);
            }
        });

        jButtonEditGoods.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small/business/swing/gui/images/edit.png"))); // NOI18N
        jButtonEditGoods.setText("Редагувати");
        jButtonEditGoods.setEnabled(false);
        jButtonEditGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditGoodsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jButtonAddGoods)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditGoods)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddGoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditGoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelStoreHouse.setBorder(javax.swing.BorderFactory.createTitledBorder("Склади"));

        jListStoreHouses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListStoreHouses);

        javax.swing.GroupLayout jPanelStoreHouseLayout = new javax.swing.GroupLayout(jPanelStoreHouse);
        jPanelStoreHouse.setLayout(jPanelStoreHouseLayout);
        jPanelStoreHouseLayout.setHorizontalGroup(
            jPanelStoreHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );
        jPanelStoreHouseLayout.setVerticalGroup(
            jPanelStoreHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        jPanelGoods.setBorder(javax.swing.BorderFactory.createTitledBorder("Список товарів на складі"));

        jTableGoods.setAutoCreateRowSorter(true);
        jTableGoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Найменування", "Заводський артикул", "Внутрішній артикул", "Кількість", "Кіл-ть на всіх складах"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGoods.getTableHeader().setReorderingAllowed(false);
        jTableGoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGoodsMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableGoodsMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableGoods);
        jTableGoods.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableGoods.getColumnModel().getColumn(0).setMaxWidth(50);
        jTableGoods.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableGoods.getColumnModel().getColumn(4).setMaxWidth(80);
        jTableGoods.getColumnModel().getColumn(5).setPreferredWidth(133);
        jTableGoods.getColumnModel().getColumn(5).setMaxWidth(133);

        javax.swing.GroupLayout jPanelGoodsLayout = new javax.swing.GroupLayout(jPanelGoods);
        jPanelGoods.setLayout(jPanelGoodsLayout);
        jPanelGoodsLayout.setHorizontalGroup(
            jPanelGoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGoodsLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanelGoodsLayout.setVerticalGroup(
            jPanelGoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGoodsLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jPanelStoreHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelGoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelStoreHouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddGoodsActionPerformed
        storeHousesService.setCurrentElement(new GoodsOnStoreHouses());
        StoreHouseGoodsElementJFrame goods = new StoreHouseGoodsElementJFrame();
        goods.pack();
        ModalFrameUtil.showAsModal(goods, this);
        getGoodsList();
    }//GEN-LAST:event_jButtonAddGoodsActionPerformed

    private void jButtonEditGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditGoodsActionPerformed
        edit();
    }//GEN-LAST:event_jButtonEditGoodsActionPerformed

    private void jTableGoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGoodsMouseClicked
        if (evt.getClickCount() == 2) {
            edit();
        }
    }//GEN-LAST:event_jTableGoodsMouseClicked

    private void jTableGoodsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGoodsMouseReleased
        svalidate();
    }//GEN-LAST:event_jTableGoodsMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreHousesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreHousesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreHousesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreHousesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StoreHousesJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddGoods;
    private javax.swing.JButton jButtonEditGoods;
    @SuppressWarnings("rawtypes")
	private javax.swing.JList jListStoreHouses;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelGoods;
    private javax.swing.JPanel jPanelStoreHouse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGoods;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("unchecked")
    private void getStoreHousesList() {
        DefaultListModel<StoreHouse> dl = new DefaultListModel<StoreHouse>();
        for (StoreHouse storeHouses : storeHousesService.getDataList()) {
            dl.addElement(storeHouses);
        }
        jListStoreHouses.setModel(dl);
    }

    private void getGoodsList() {
        DefaultTableModel dataModel = (DefaultTableModel) jTableGoods.getModel();
        dataModel.setRowCount(0);
        //if (storeHousesService.getCurrentElement().getGoods() != null) {
        for (GoodsOnStoreHouses goods : storeHousesService.getGoods()) {
            Object[] g = new Object[]{goods.getId(), goods, goods.getNomenclature().getArticleofgoods(), goods.getNomenclature().getArticleinside(), goods.getQuantity(), goods.getNomenclature().getQuantity()};
            dataModel.addRow(g);
        }
        //}
    }

    private void edit() {
        if (storeHousesService.isCanEditGoods()) {
            StoreHouseGoodsElementJFrame oe = new StoreHouseGoodsElementJFrame();
            oe.pack();
            ModalFrameUtil.showAsModal(oe, this);
            getGoodsList();
        }
    }

    private void svalidate() {
        GoodsOnStoreHouses validateElement = null;
        if (jTableGoods.getSelectedRow() >= 0) {
            validateElement = (GoodsOnStoreHouses) jTableGoods.getValueAt(jTableGoods.getSelectedRow(), OBJECT_COLUMN);
        }
        storeHousesService.setCurrentElement(validateElement);
        storeHousesService.validate();
        jButtonAddGoods.setEnabled(storeHousesService.isCanAddGoods());
        jButtonEditGoods.setEnabled(storeHousesService.isCanEditGoods());
    }
}